### ISSUE TITLE
Where can i purchase this

### ISSUE THREAD

**Issue by Charlie1093** [fuwu99/yugen#1]

**Comment by fuwu99** [comment]
hello @Bluefate1010 ! Please kindly inbox me on facebook via this link: https://www.facebook.com/cynthiavo11/

**Comment by Charlie1093** [comment]
can i email you by anychance i dont have facebook

**Comment by fuwu99** [comment]
or you can give me your discord tag instead! if you aren't comfortable sharing it, heres my email! [milk.yy2k@gmail.com]
